routes/web.php
<?php

use App\Events\eventTrigger;
Route::get('/','WelcomeController@index')->name('WelcomeController');
Route::get('/contacts','ContactsController@index')->name('ContactsController');
Route::get('/menus/{name_trans}-{id}','MenusController@index')->name('menus');
Route::post('ajax/mailer','AjaxController@mailer')->name('mailer');

// Admin base page
Route::get('/admin', function () {
    return redirect('/admin/home');
});

// Authentication Routes...
$this->get('login', 'Auth\LoginController@showLoginForm')->name('auth.login');
$this->post('login', 'Auth\LoginController@login')->name('auth.login');
$this->post('logout', 'Auth\LoginController@logout')->name('auth.logout');

// Change Password Routes...
$this->get('change_password', 'Auth\ChangePasswordController@showChangePasswordForm')->name('auth.change_password');
$this->patch('change_password', 'Auth\ChangePasswordController@changePassword')->name('auth.change_password');

// Password Reset Routes...
$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('auth.password.reset');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('auth.password.reset');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
$this->post('password/reset', 'Auth\ResetPasswordController@reset')->name('auth.password.reset');

Route::group(['middleware' => ['auth'], 'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::resource('pictures', 'Admin\PictureController');
    Route::put('pictures', 'Admin\PictureController@store')->name('pictures.store');
    Route::delete('products_images/{productsImage}', 'Admin\ProductsController@destroyPicture')->name('productPicture.destroy');

    Route::get('/home', 'HomeController@index');
    Route::resource('settings', 'Admin\SettingsController');
    Route::resource('menus', 'Admin\MenusController');
    Route::resource('catalog', 'Admin\CatalogController');
    Route::resource('products', 'Admin\ProductsController');
    Route::resource('texts', 'Admin\TextsController');
    Route::post('ajax/refreshCategoriesTree','Admin\AjaxController@refreshCategoriesTree')->name('refreshCategoriesTree');
    Route::post('ajax/refreshMenusTree','Admin\AjaxController@refreshMenusTree')->name('refreshMenusTree');
    Route::post('ajax/toggleWatch','Admin\AjaxController@toggleWatch')->name('toggleWatch');

    Route::resource('permissions', 'Admin\PermissionsController');
    Route::post('permissions_mass_destroy', ['uses' => 'Admin\PermissionsController@massDestroy', 'as' => 'permissions.mass_destroy']);
    Route::resource('roles', 'Admin\RolesController');
    Route::post('roles_mass_destroy', ['uses' => 'Admin\RolesController@massDestroy', 'as' => 'roles.mass_destroy']);
    Route::resource('users', 'Admin\UsersController');
    Route::post('users_mass_destroy', ['uses' => 'Admin\UsersController@massDestroy', 'as' => 'users.mass_destroy']);

});

Route::get('/alertBox', function () {
    return view('eventListener');
});
Route::get('/fireEvent', function () {
event(new eventTrigger());
});

app/Menu.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Collective\Html\FormFacade;
use App\MenusMenu;

class Menu extends Model
{
    protected $fillable = ['name', 'name_trans', 'watch', 'short_text', 'text', 'url',
        'target', 'seo_title', 'seo_description', 'seo_keywords', 'root'];

    /**
     * Get the related menus through menus_menus table
     */
    public function menus_menus()
    {
        // return $this->hasMany('App\MenusMenu')->;
        return $this->hasManyThrough(
            'App\Menu',//menu model
            'App\MenusMenu',//menus_menus(through) table
            'menu_id',//first key of menus_menus
            'id',//3d table (menu) key
            'id',
            'next_menu_id');// far key of menus_menus
    }

    /* recursive function
     * @return generates nestable html
     */
    public function generate_nestable($str = "", $root = 1)
    {
        if ($this->id) {//generate item html
            $id = $this->id;
            $name = $this->name;
            if ($this->watch == 0) {
                $iw = "<a title='" . __("global.turn_on") . "' data-orm='Menu' data-id='{$this->id}'  class=\"btn btn-xs btn-warning toggleWatch\">" . __("global.not_act") . "</a>\n";
            } else {
                $iw = "<a title='" . __("global.turn_off") . "' data-orm='Menu' data-id='{$this->id}' class=\"btn btn-xs btn-success toggleWatch\">" . __("global.act") . "</a>\n";
            }

            $f = FormFacade::open(array(
                'style' => 'display: inline-block;',
                'method' => 'DELETE',
                'onsubmit' => "return confirm('" . trans("global.app_are_you_sure") . "');",
                'route' => ['admin.menus.destroy', $this->get('id')]));
            $f .= FormFacade::submit(trans('global.app_delete'), array('class' => 'btn btn-xs btn-danger'));
            $f .= FormFacade::close();
            $str .= "<li class=\"category_item dd-item dd3-item\" data-id=\"$this->id\">\n";
            $str .= "                                            <div class=\"dd-handle dd3-handle\"></div>\n";
            $str .= "                                            <div class=\"dd3-content\">\n";
            $str .= "{$this->get('name')}\n";
            $str .= "                                                <div class=\"tools_col\">\n";
            $str .= "  $f\n";
            $str .= "                                                </div>\n";
            $str .= "                                                <div class=\"tools_col\">\n";
            $str .= "<a href=" . route('admin.menus.edit', [$this->get('id')]) . " class=\"btn btn-xs btn-info\">" . __('global.app_edit') . "</a>\n";
            $str .= "                                                </div>\n";
            $str .= "                                                <div class=\"tools_col\">\n";
            $str .= "                                                  $iw\n";
            $str .= "                                                </div>\n";
            $str .= "                                            </div>\n";
            $next = $this->adm_childs();
            if (count($next) > 0) {
                $str .= "<ol class=\"dd-list\">\n";
            }
            foreach ($next as $one) {
                $str = $one->generate_nestable($str, $root);
            }
            if (count($next) > 0) {
                $str .= "</ol>\n";
            }
            $str .= "</li>\n";

        } else {//load root items and re-run objects
            $next = $this->adm_roots($root);
            foreach ($next as $one) {
                $str = $one->generate_nestable($str, $root);
            }
        }
        return $str;
    }

    /*
     * loads root menus
     * @param int $root default=1
     */
    public function adm_roots($root = 1)
    {
        return
            $this->where("root", $root)->get();

    }

    /*
    * loads root published menus
    * @param int $root default=1
    */
    public function roots($root = 1)
    {
        return
            $this->where(
                [
                    "root" => $root,
                    "watch" => "1"
                ]
            )->get();

    }

    /*
     * load all related childs
     */
    public function adm_childs()
    {
        return $this->menus_menus;
    }

    /*
     * get published childs
     */
    public function childs()
    {
        return $this
            ->menus_menus
            ->where("watch", "1");
    }

    /*
     * get table column
     */
    public function get($column)
    {
        return $this->$column;
    }

    public static function refreshMenusTree($request)
    {
        MenusMenu::query()->truncate();//clear all relation
        self::refreshRecursive($request);//recursive create new relations on menus_menus table
    }

//recursive create new relations on menus_menus table
    static function refreshRecursive($request, $i = 0, $pid = false)
    {
        foreach ($request as $one) {
            $i++;
            $id = $one->id;
            $em = Menu::where("id", $id)->first();
            if (!$em->id) {// no object - send relode command (maybe someone delete it recently)
                die(json_encode(array("reload" => true, "id" => $id)));
            }
            if ($pid) {/// if got father - clear the root
                $em->root = 0;
            } else {//if becomes root clear father rels
                $em->root = 1;
                MenusMenu::where('next_menu_id', $id)->delete();//clear relation
            }
            $em->order = $i;
            $em->save();
            if ($pid) { //check we have relation to given father, add if it's have not
                $rel = MenusMenu::where("next_menu_id", $em->id)->first();
                if ($rel === null) {
                    $rel = new MenusMenu;
                    $rel->menu_id = $pid;
                    $rel->next_menu_id = $em->id;
                    $rel->save();
                }
            }
            if (isset($one->children)) {
                self::refreshRecursive($one->children, $i, $em->id);
            } else {/// no childs then delete exists
                MenusMenu::where('menu_id', $id)->delete();//clear relation
            }
        }
    }

    /**
     * generate html recursiv menus tree using menus dependencies
     * @param int $root
     * @param string $html
     * @return HTML
     */
    public function generate_menus($root = 1, $html = "")
    {

        if ($this->id) {//generate item html
            $id = $this->id;
            $name = $this->get('name');
            $url = self::get_url($this);//get url depending on menu type
            $html .= "<li>\n";
            $html .= "<a href=\"$url\">$name</a>\n";
            $next = $this->childs();
            if (count($next) > 0) {
                $html .= " <ul>\n";
            }
            foreach ($next as $one) {
                $html = $one->generate_menus($root, $html);
            }
            if (count($next) > 0) {
                $html .= "</ul>\n";
            }
            $html .= "</li>\n";

        } else {//load root items and re-run objects
            $next1 = $this->roots($root);

            foreach ($next1 as $one) {
                $html = $one->generate_menus($root, $html);
            }

        }

        return $html;
        /*  $tree = "";
          $tree .= "<ul>\n";
          $tree .= "                <li><a href=\"#\">Кнопка меню</a></li>\n";
          $tree .= "                <li class=\"active\">\n";
          $tree .= "                    <a href=\"#\">Кнопка меню</a>\n";
          $tree .= "                    <ul>\n";
          $tree .= "                        <li><a href=\"#\">Кнопка подменю 1</a></li>\n";
          $tree .= "                        <li><a href=\"#\">Кнопка подменю 2</a></li>\n";
          $tree .= "                        <li><a href=\"#\">Кнопка подменю 3</a></li>\n";
          $tree .= "                        <li><a href=\"#\">Кнопка подменю 4</a></li>\n";
          $tree .= "                        <li><a href=\"#\">Кнопка подменю 5</a></li>\n";
          $tree .= "                    </ul>\n";
          $tree .= "                </li>\n";
          $tree .= "                <li><a href=\"#\">Кнопка меню</a></li>\n";
          $tree .= "                <li><a href=\"#\">Кнопка меню</a></li>\n";
          $tree .= "                <li><a href=\"#\">Кнопка меню</a></li>\n";
          $tree .= "                <li><a href=\"#\">Кнопка меню</a></li>\n";
          $tree .= "            </ul>\n";*/

    }

    /* generate menu url depending on menu type
     * @param object $menu
     * @return string URL
     */
    private static function get_url(Menu $menu)
    {
        if ($menu->controller) {
            return route($menu->controller);
        } else {
            return route('menus', ['name_trans' => $menu->name_trans, 'id' => $menu->id]);
        }
    }

    /*
     * get system object by system variables
     * @param string Controller
     * @param string Method
     * @return object - menu table
     */
    public static function ControllerMethod($controller, $method = "")
    {
        return self::where([
            'controller' => $controller,
            'method' => $method,
            'watch' => '1'
        ])->first();
    }

    /* get object by given fields or throw 404
     * @param array associative array of fields
     * @return object|404
     */
    public static function by_fields(array $array)
    {
        return self::where($array)->firstOrFail();
    }
}

app/Http/Controllers/Admin/MenusController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UpdateMenusRequest;
use App\Http\Requests\Admin\StoreMenusRequest;
use App\Menu;
use App\Http\Traits\AdminTrait;

class MenusController extends Controller
{
    use AdminTrait; // load data used on each page

    public function __construct()
    {
        $this->parse_data();// load data used on each page using AdminTrait
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $object = new Menu();
        $nestable = $object->generate_nestable();
        return view('admin.menus.tree', compact(['nestable']));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $object = new Menu();
        $route = ['admin.menus.store'];
        $title = __('global.menus.create');
        $method = 'POST';
        return view('admin.menus.create', compact(['object', 'route', 'method', 'title']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\Admin\StoreMenusRequest
     * @return \Illuminate\Http\Response
     */
    public function store(StoreMenusRequest $request)
    {

        $object = Menu::create($request->all());
        return redirect()->route('admin.menus.index');
        //return redirect()->route('admin.menus.show', [$object->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $object = Menu::findOrFail($id);
        $route = ['admin.menus.update', $id];
        $title = __('global.menus.edit') . " " . $object->get('name');
        $method = 'PUT';
        return view('admin.menus.create', compact(['object', 'route', 'method', 'title']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\Admin\UpdateMenusRequest
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateMenusRequest $request, $id)
    {

        $object = Menu::findOrFail($id);
        $object->update($request->all());
        return redirect()->route('admin.menus.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $object = Menu::findOrFail($id);
        $object->delete();
        return redirect()->route('admin.menus.index');
    }


}

app/Http/Controllers/MenusController.php
<?php

namespace App\Http\Controllers;

use App\Menu;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class MenusController extends FatherController
{
    //
    /*
     * generate one menu object page
     * @param Request $request
     * @return html menu object page
     */
    public function index(Request $request)
    {
        $id = $request->route('id');
        $name_trans = $request->route('name_trans');
        $object = Menu::by_fields(['name_trans' => $name_trans, 'id' => $id, 'watch' => 1]);
        return view('frontend.menus', compact(['object']));
    }
}

resources/views/admin/menus/create.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">{{$title}}</h3>

    {!! Form::model($object, ['method' => $method,'route' => $route, 'files' => true]) !!}

    <div class="box box-primary">
        {{--<div class="box-header with-border">
            @lang('global.app_edit')
        </div>--}}

        <div class="box-body">
            <div class="row">
                <div class="col-xs-12 form-group @if($errors->has('name')) has-error @endif">
                    {!! Form::label('name', __('global.menus.name'), ['class' => 'control-label']) !!}
                    {!! Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name'))
                        <p class="help-block">
                            {{ $errors->first('name') }}
                        </p>
                    @endif
                </div>

                <div class="col-xs-12 form-group @if($errors->has('name_trans')) has-error @endif">
                    {!! Form::label('name_trans', __('global.menus.name_trans'), ['class' => 'control-label']) !!}
                    {!! Form::text('name_trans', old('name_trans'), ['class' => 'form-control', 'placeholder' => '', 'required' => '']) !!}
                    <p class="help-block"></p>
                    @if($errors->has('name_trans'))
                        <p class="help-block">
                            {{ $errors->first('name_trans') }}
                        </p>
                    @endif
                </div>
                <div class="col-xs-12 form-group">
                    {!! Form::label('watch', __('global.menus.watch'), ['class' => 'control-label']) !!}

                    {!! Form::select('watch', ['0'=>__('global.app_watch0'),'1'=>__('global.app_watch1')], old('watch'), ['class' => 'form-control select22', 'required' => '']) !!}

                </div>

                <div class="col-xs-12 form-group">
                    {!! Form::label('short_text', __('global.menus.short_text'), ['class' => 'control-label']) !!}
                    {!! Form::textarea('short_text', old('short_text'), ['class' => 'form-control', 'placeholder' => '', 'required' => false]) !!}

                </div>

                <div class="col-xs-12 form-group">
                    {!! Form::label('text', __('global.menus.text'), ['class' => 'control-label']) !!}
                    {!! Form::textarea('text', old('text'), ['class' => 'form-control ckeditor', 'placeholder' => '', 'required' => '']) !!}
                    @section('javascript')
                        <script src="{{ url('plugins/ckeditor/ckeditor.js') }}"></script>
                        <script src="{{ url('plugins/ckfinder/ckfinder.js') }}"></script>
                        <script>
                            CKFinder.setupCKEditor(CKEDITOR, '/plugins/ckfinder/');
                        </script>
                        @yield('javascript')
                    @overwrite


                </div>
            </div>


        </div>
    </div>

    {!! Form::submit(trans('global.app_update'), ['class' => 'btn btn-danger']) !!}
    {!! Form::close() !!}
@stop

resources/views/admin/menus/tree.blade.php
@extends('layouts.app')

@section('content')
    <h3 class="page-title">@lang('global.menus.tree')</h3>
    <p>
        <a href="{{route('admin.menus.create')}}" class="btn btn-success">{{__('global.menus.create')}}</a>
    </p>

    <div class="box box-primary">
        <div class="box-header with-border">
            @lang('global.menus.tree')
        </div>

        <div class="box-body">


                <div class="dd" id="nestable">
                    <ol class='dd-list dd3-list'>
                        {!!$nestable!!}
                    </ol>
                </div>


        </div>
    </div>
@section('javascript')

    <script src="{{ url('plugins/nestable2/jquery.nestable.min.js') }}"></script>
    <script src="{{ url('plugins/nestable2/ui-nestable.js') }}"></script>
    <script>
        var nestableUrl="{{route('admin.refreshMenusTree')}}";
        UINestable.init(
            {
                maxDepth: 1
            }
        );
       // $('#nestable').nestable('collapseAll');
    </script>
    @yield('javascript')
@overwrite
@section('css')
    <link rel="stylesheet"
          href="{{ url('plugins/nestable2/jquery.nestable.min.css') }}"/>
    <link rel="stylesheet"
          href="{{ url('plugins/nestable2/nestableCustom.css') }}"/>

    @yield('css')
@overwrite
@stop